### ISSUE TITLE
Bowser Castle Keys

### ISSUE THREAD

**Issue by piefish1996** [Phantom5800/pmr-tracker#93]
Why were the Bowser's Castle Keys removed from the items in the tracker? Is this a mistake or were these removed on purpose?

**Comment by christianlegge** [comment]
Just to make sure, you're looking at the Required Tracker when Power Star Hunt is on, right? That's the only way I could replicate the issue. If so, fixed in #94. If not, please export all your tracker data by clicking "Export Tracker Data" in the top right, checking all the boxes, and post the result here.

**Comment by piefish1996** [comment]
I do have Power Star Hunt turned on, but I still can't see the  castle keys.. I could be doing something wrong lol

But here's what I assume you're looking for? 
[pmr-tracker-2023-11-20T21_50_22.956Z.json](https://github.com/Phantom5800/pmr-tracker/files/13419724/pmr-tracker-2023-11-20T21_50_22.956Z.json)

**Comment by christianlegge** [comment]
It hasn't been fixed yet. The pull request is in though and it will fix this issue once merged and the site updated. Thanks for reporting!
